#!/bin/bash
echo -n "./, ../, "; find . -maxdepth 1 -type d ! -name '.' ! -name '..' -printf "%f/," | LC_ALL=C sort -d | tr '\n' ',' | sed 's/,$/\n/'; find . -maxdepth 1 -type f ! -name '.*' | LC_ALL=C sort -d | tr '\n' ',' | sed 's/,$/\n/'
